language: node_js
sudo: true
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
services:
- mysql
node_js:
- '9'
directories:
- node_modules
before_install:
- mkdir -p  ~/.ssh/
- openssl aes-256-cbc -K $encrypted_eaa6087fa539_key -iv $encrypted_eaa6087fa539_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.252.230 \n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade -uroot -proot
- sudo service mysql restart
- mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS vote_test;'
install:
- npm install
before_script:
script:
 - npm run ci
after_success:
- tar -jcf egg.tar.bz2 * .*
- scp egg.tar.bz2 ubuntu@123.207.252.230:~/
- ssh ubuntu@123.207.252.230 'mkdir -p /usr/share/nginx/html/egg && mv ~/egg.tar.bz2
  /usr/share/nginx/html/egg'
- ssh ubuntu@123.207.252.230 'cd /usr/share/nginx/html/egg && tar -jxf egg.tar.bz2
  && rm -rf egg.tar.bz2'
- ssh ubuntu@123.207.252.230 'cd /usr/share/nginx/html/egg && npm run stop'
- ssh ubuntu@123.207.252.230 'cd /usr/share/nginx/html/egg && npm run start'
# - ssh ubuntu@123.207.252.230 'pm2 show vote'
after_script:
branches:
  only:
  - master
env:
  global:
